.TH dwindows-config 1 "12 Apr 2009" "dwindows" "GNU/Linux"
.SH NAME
dwindows-config \- get information about installed dwindows library
.SH SYNOPSIS
.B dwindows-config
[\fIOPTION\fR] ...
.SH DESCRIPTION
Provides information about dwindows library.

Known values for OPTION are:
.TP
\fB\-\-prefix\fR
print dwindows prefix
.TP
\fB\-\-libs\fR
print library linking information
.TP
\fB\-\-cflags\fR
print preprocessor flags, I_opts, and compiler options
.TP
\fB\-\-help\fR
print this help and exit
.TP
\fB\-\-version\fR
print version information
.SH "AUTHOR"
This manpage has been written by Mark hessling <mark@rexx.org>
based on libpng12-config.1.


